# Generated by Django 5.0.4 on 2024-05-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='zone_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('age', models.IntegerField(null=True)),
                ('salary', models.CharField(max_length=255)),
                ('working_hours', models.CharField(max_length=255)),
            ],
        ),
    ]
