# Generated by Django 5.0.4 on 2024-05-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=225)),
                ('job', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
            ],
        ),
    ]
