# Generated by Django 5.0.4 on 2024-05-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('typ', models.CharField(max_length=225)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
