# Generated by Django 5.0.6 on 2024-05-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=225)),
                ('make', models.CharField(max_length=225)),
                ('color', models.CharField(max_length=15)),
                ('price', models.IntegerField(max_length=115)),
            ],
        ),
    ]
