# Generated by Django 5.0.6 on 2024-05-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='price',
            field=models.IntegerField(),
        ),
    ]
